name = "star6nine-site"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-09-04"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"